# Generated by Django 4.1 on 2022-08-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nombre')),
                ('app', models.CharField(max_length=50, verbose_name='apellido paterno')),
                ('apm', models.CharField(max_length=50, verbose_name='apellido materno')),
                ('tel', models.CharField(max_length=10, null=True, verbose_name='telefono')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('add', models.CharField(max_length=250, verbose_name='dirección')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
